name: Prepare polkadot binaries
description: Downloads and configures prebuilt Polkadot binaries
runs:
  using: composite
  steps:
    - name: Download polkadot binaries
      uses: dawidd6/action-download-artifact@e7466d1a7587ed14867642c2ca74b5bcc1e19a2d # v3.0.0
      with:
        workflow: build-polkadot-for-nightly.yml
        name: nightly-polkadot-binary
        path: ./tmp

    - name: Setup permissions and move to path
      shell: bash
      run: |
        chmod u+x ./tmp/target/release/polkadot*
        ./tmp/target/release/polkadot --version
        mkdir -p ${HOME}/.local/bin
        echo "${HOME}/.local/bin" >> $GITHUB_PATH
        mkdir -p ${HOME}/.config/polkadot-staking-miner
        mv ./tmp/target/release/polkadot* ${HOME}/.local/bin
        mv ./tmp/parachain.json ${HOME}/.config/polkadot-staking-miner
        mv ./tmp/rc.json ${HOME}/.config/polkadot-staking-miner
